//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTermStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212031Entities : DbContext
    {
        public APD65_63011212031Entities()
            : base("name=APD65_63011212031Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerComStore> CustomerComStores { get; set; }
        public virtual DbSet<EmployeesComStore> EmployeesComStores { get; set; }
        public virtual DbSet<IncomeComStore> IncomeComStores { get; set; }
        public virtual DbSet<OrderComStore> OrderComStores { get; set; }
        public virtual DbSet<OrderDetailComStore> OrderDetailComStores { get; set; }
        public virtual DbSet<ProductStockComStore> ProductStockComStores { get; set; }
        public virtual DbSet<PromotionComStore> PromotionComStores { get; set; }
    }
}
