//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTermStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderComStore()
        {
            this.IncomeComStores = new HashSet<IncomeComStore>();
            this.OrderDetailComStores = new HashSet<OrderDetailComStore>();
        }
    
        public int oId { get; set; }
        public System.DateTime date { get; set; }
        public decimal total { get; set; }
        public int cId { get; set; }
    
        public virtual CustomerComStore CustomerComStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeComStore> IncomeComStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailComStore> OrderDetailComStores { get; set; }
    }
}
