//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTermStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailComStore
    {
        public int odId { get; set; }
        public int pId { get; set; }
        public int amount { get; set; }
        public int oId { get; set; }
    
        public virtual OrderComStore OrderComStore { get; set; }
        public virtual ProductStockComStore ProductStockComStore { get; set; }
    }
}
