//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTermStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionComStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionComStore()
        {
            this.ProductStockComStores = new HashSet<ProductStockComStore>();
        }
    
        public int promotionId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int sellprice { get; set; }
        public int sellpercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStockComStore> ProductStockComStores { get; set; }
    }
}
